### ISSUE TITLE
Panel de edición del usuario

### ISSUE THREAD

**Issue by KarlHeitmann** [KarlHeitmann/survey_express_normal#18]
Permitir al usuario que pueda editar sus datos personales: email, nombre. Recuerde que al modificar el email del usuario, también le va a cambiar su imagen de gravatar.

- 2 puntos para el examen

**Comment by JosephM2425** [comment]
Karl yo voy a trabajar en este

**Comment by KarlHeitmann** [comment]
Bien!!! Asignado!!!
